title: John Zech
url: "https://jrzech.github.io"

baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/jrzech"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "Contact"
   link: "contact"
 - name: "Google Scholar"
   link: "https://scholar.google.com/citations?user=s1apa_4AAAAJ&hl=en"
 - name: "Medium"
   link: "https://medium.com/@jrzech"
 - name: "Twitter"
   link: "https://twitter.com/johnrzech?lang=en"
 - name: "LinkedIn"
   link: "https://www.linkedin.com/in/john-zech-82b418142"
