title: Researcher
url: "https://jrzech.github.io"

baseurl: "/jrzech.github.io"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/jrzech"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Contact"
   link: "contact"
 - name: "Google Scholar"
   link: "gscholar"
 - name: "Medium"
   link: "medium"
 - name: "Twitter"
   link: "twitter"
 - name: "LinkedIn"
   link: "linkedin"
